/* ==================== 图片数据（回忆卡片 + 心形照片共用） ==================== */
const NUM_PHOTOS = 42;
function imgUrl(prompt, seed){return `img/${seed+1}.jpg`}

const imagePrompts = [
  "Dreamy pink cherry blossom path with falling petals, pastel, bokeh",
  "Fantasy castle under purple starry sky, dreamy pastel illustration, sparkles",
  "Pink fluffy clouds at golden sunset, dreamy atmosphere, pastel colors",
  "Open vintage crystal music box with magical light, pink purple fantasy",
  "Field of pink flowers under soft rainbow, dreamy pastel landscape",
  "White unicorn in enchanted pastel forest, dreamy fantasy art, sparkles",
  "Floating paper lanterns in purple pink night sky, dreamy bokeh",
  "Vintage pink bicycle with flower basket, dreamy pastel spring scene",
  "Hot air balloons over pastel mountain range, dreamy sunset",
  "Pink rose garden with fairy lights, dreamy soft focus, pastel",
  "Moonlit lake with pink lotus flowers, dreamy pastel night scene",
  "Sparkling birthday cake with pink candles, dreamy pastel celebration",
  "Snowy pastel pine forest at twilight with magical lights, dreamy",
  "Magical fairy tea party on pastel clouds, dreamy fantasy, sparkles",
  "Pastel butterfly garden with glowing flowers, dreamy soft focus",
  "Crystal palace under aurora borealis, dreamy pastel purple fantasy",
  "Dreamy pastel carousel with golden horses, magical bokeh lights",
  "Floating crystal balloons in pink purple sky, dreamy soft focus",
  "Pastel rainbow waterfall in enchanted valley, dreamy fantasy landscape",
  "Magical fairy library with floating books, dreamy pastel interior",
  "Pastel sakura petals floating on dreamy lake, mirror reflection",
  "Enchanted pastel mushroom forest, dreamy fantasy world, bokeh lights",
  "Pastel starry desert with magical oasis, dreamy pink purple fantasy",
  "Crystal peacock with pastel feathers, dreamy fantasy art, sparkles",
  "Pastel candy kingdom with lollipop towers, dreamy fantasy, sparkles",
  "Magical pastel waterfall glowing under stars, dreamy night scene",
  "Dreamy pastel sky lantern festival, hundreds of floating lanterns",
  "Crystal rose frozen in ice, dreamy pastel winter scene, bokeh",
  "Pastel mermaid on magical coral reef, dreamy ocean fantasy, sparkles",
  "Glowing pastel jellyfish floating in night sky, dreamy fantasy",
  "Dreamy pastel fox with nine tails, cherry blossom petals, magical",
  "Pastel dragon flying over rainbow mountains, dreamy fantasy art",
  "Dreamy pastel clock tower in cloud city, magical sunset, bokeh",
  "Crystal violin with glowing pastel notes, dreamy music fantasy",
  "Pastel swan on dreamy pink lake at sunrise, soft pastel bokeh",
  "Dreamy pastel phoenix rising from pink flames, fantasy art",
  "Magical pastel owl on glowing mushroom, dreamy night forest",
  "Pastel dreamcatcher with pink feathers, dreamy soft focus",
  "Dreamy pastel galaxy swirl with stars and nebula, magical",
  "Crystal fairy wings with pastel light, dreamy fantasy portrait",
  "Pastel moon castle floating in clouds, dreamy fantasy night",
  "Dreamy pastel candy cane forest with sparkles, magical winter"
];
const imageUrls = imagePrompts.map((prompt, idx) => imgUrl(prompt, idx));

const memoryCaptions = [
  '樱花飘落的小径 · 初遇的春天',
  '星空下的城堡 · 童话的开始',
  '粉色云端的黄昏 · 温柔的午后',
  '水晶八音盒 · 珍藏的秘密',
  '彩虹下的花海 · 一起许过的愿',
  '独角兽的森林 · 梦境的入口',
  '天灯升起的夜 · 心愿的寄托',
  '粉色单车的午后 · 青春的剪影',
  '热气球升空 · 远方的召唤',
  '玫瑰园的光点 · 浪漫的约定',
  '月光下的荷塘 · 静谧的回忆',
  '生日蛋糕的烛光 · 今日的主角',
  '雪夜的松林 · 一起走过的小路',
  '云端茶会 · 童话里的一天',
  '蝴蝶花径 · 春日的小确幸',
  '极光下的水晶宫 · 童话梦境',
  '旋转木马 · 童年与现在',
  '水晶气球 · 漂浮的幻想',
  '彩虹瀑布 · 倾泻的时光',
  '魔法图书馆 · 翻开的章节',
  '樱花湖面 · 倒影中的你我',
  '蘑菇森林 · 童年的探险',
  '星空绿洲 · 沙漠的奇迹',
  '水晶孔雀 · 绽开的回忆',
  '糖果王国 · 甜入心扉的一天',
  '星光下的瀑布 · 梦幻银河',
  '天灯节 · 一千个心愿升空',
  '冰封玫瑰 · 晶莹的誓言',
  '珊瑚礁的美人鱼 · 海底童话',
  '夜空中漂浮的水母 · 发光的梦',
  '九尾狐 · 樱花下的倩影',
  '彩虹山的飞龙 · 守护者的低语',
  '云端钟塔 · 时光的指针',
  '水晶小提琴 · 流动的旋律',
  '晨曦中的天鹅 · 静谧的优雅',
  '粉焰凤凰 · 重生的希望',
  '魔法猫头鹰 · 森林的智者',
  '捕梦网 · 留住每一个好梦',
  '星系漩涡 · 宇宙的呼吸',
  '水晶仙翼 · 闪烁的光尘',
  '月宫城堡 · 漂浮的仙境',
  '拐杖糖森林 · 甜蜜的冬天',
];
